backend:
  name: github
  repo: TechRich/TechRich.github.io
  branch: main
  # For local-only editing you can ignore OAuth details; use the local backend instead.

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow
site_url: "https://about.techrich.net"
logo_url: "/favicon.svg"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/docs/index.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Template", name: "template", widget: "select", options: ["splash", "doc"], required: false }
          - { label: "Hero Tagline", name: "hero.tagline", widget: "string", required: false, hint: "Shown when template is splash" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "src/content/docs/about.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/content/docs/contact.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General"
        name: "general"
        file: "src/content/settings/site.json"
        format: "json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Site Description", name: "site_description", widget: "string", required: false }
          - { label: "Homepage Tagline", name: "homepage_tagline", widget: "string", required: false }
          - { label: "GitHub", name: "social_github", widget: "string", required: false }
          - { label: "LinkedIn", name: "social_linkedin", widget: "string", required: false }
          - { label: "Email", name: "email", widget: "string", required: false }

  - name: "guides"
    label: "Guides"
    label_singular: "Guide"
    folder: "src/content/docs/guides"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    summary: "{{title}} — {{description}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "reference"
    label: "Reference"
    folder: "src/content/docs/reference"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
